### ISSUE TITLE
PA Review: User Authentication 

### ISSUE THREAD

**Issue by 93lykevin** [93lykevin/StreetX#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Looking SO awesome Kevin!! Just one last thing to update.  Reduce the space between the header and the top of the session form when trying to sign up so its more horizonally centered.
