### ISSUE TITLE
Seachbar MVP

### ISSUE THREAD

**Issue by 93lykevin** [93lykevin/StreetX#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Bonus improvements for later: 
- when typing in, allow use of keys to select item from the dropdown and hit enter to go to that item
- return search results for related items (user doesn't click on specific item to look at - eg. type in "nike" and hit enter and you see nike products as an index page)

**Comment by jenkennedy** [comment]
Great job!!

**Comment by jenkennedy** [comment]
Great job!
